/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#994700",
        "on-surface-variant": "#43474f",
        tertiary: "#141819",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#ffb68b",
        "primary-container": "#002b5b",
        "error-container": "#ffdad6",
        "tertiary-container": "#292c2e",
        "surface-tint": "#405f91",
        "on-primary-fixed-variant": "#264778",
        "on-primary-container": "#7594ca",
        "on-secondary-fixed": "#321200",
        "on-secondary-container": "#592600",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c4c7c9",
        "primary-fixed": "#d6e3ff",
        "on-secondary-fixed-variant": "#753400",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#909395",
        surface: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        background: "#f8f9ff",
        "primary-fixed-dim": "#a9c7ff",
        "inverse-surface": "#213145",
        "inverse-primary": "#a9c7ff",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        "outline-variant": "#c4c6d0",
        "on-background": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        error: "#ba1a1a",
        "secondary-container": "#fb7800",
        "surface-container": "#e5eeff",
        primary: "#001736",
        outline: "#747780",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#191c1e",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed": "#001b3d",
        "tertiary-fixed": "#e0e3e5",
        "secondary-fixed": "#ffdbc8",
        "on-tertiary-fixed-variant": "#444749",
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
